# Generated by Django 4.0.4 on 2022-04-14 03:06

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=model_utils.fields.StatusField(choices=[('normal_user', 'Normal User Role'), ('admin', 'Admin User Role')], default='normal_user', max_length=100, no_check_for_status=True),
        ),
    ]
